// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Enable_UIAutomation.Features.Factfind_V2.Client.FactFind.PersonalDetails
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("PersonalDetails", new string[] {
            "Reg"}, Description="\tAs an advisor\r\n\tI want to manage client personal details\r\n\tSo i can provide the " +
        "most appropriate factfind possible", SourceFile="Features\\Factfind_V2\\Client\\FactFind\\PersonalDetails\\PersonalDetails.feature", SourceLine=1)]
    public partial class PersonalDetailsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PersonalDetails.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PersonalDetails", "\tAs an advisor\r\n\tI want to manage client personal details\r\n\tSo i can provide the " +
                    "most appropriate factfind possible", ProgrammingLanguage.CSharp, new string[] {
                        "Reg"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AddPersonalDetailsOfAClient(string factfind, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LoginEnableTaur"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Personal details of a client", null, @__tags);
#line 8
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
 testRunner.Given("I am on Clients search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I select the newly created client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I click on Fact Find button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("I select the existing \"{0}\"", factfind), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I enter mandatory personal details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I save the personal details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I navigate to FactFind via breadcrumb", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And(string.Format("I select the existing \"{0}\"", factfind), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.When("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("I see the personal details saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Personal details of a client, Schroders Personal Wealth Individual Fact Find", new string[] {
                "LoginEnableTaur"}, SourceLine=22)]
        public virtual void AddPersonalDetailsOfAClient_SchrodersPersonalWealthIndividualFactFind()
        {
#line 8
this.AddPersonalDetailsOfAClient("Schroders Personal Wealth Individual Fact Find", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Edit Personal details of a client", new string[] {
                "Smoke",
                "Report",
                "LoginEnableTaur"}, SourceLine=27)]
        public virtual void EditPersonalDetailsOfAClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit Personal details of a client", null, new string[] {
                        "Smoke",
                        "Report",
                        "LoginEnableTaur"});
#line 28
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 29
 testRunner.Given("I am on Clients search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.And("I select the newly created client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("I click on Fact Find button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("I exclude the partner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I select the existing \"Schroders Personal Wealth Individual Fact Find\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Place of birth",
                        "UK Domiciled",
                        "UK resident for tax",
                        "State of Health",
                        "Smoker",
                        "Main occupation",
                        "Employment Status",
                        "Employer/Business name",
                        "Time in current employment"});
            table1.AddRow(new string[] {
                        "Sussex barn",
                        "Yes",
                        "Yes",
                        "Excellent",
                        "No",
                        "refuse consultant",
                        "Employed",
                        "Best practice IFA",
                        "7 Months"});
#line 35
 testRunner.And("I edit the following personal details", ((string)(null)), table1, "And ");
#line 38
 testRunner.And("I save the personal details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I navigate to \"Fact Find\" via breadcrumb", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I select the existing \"Schroders Personal Wealth Individual Fact Find\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.When("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("I see the personal details updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Personal Details changes update Client Summary", new string[] {
                "LoginEnableTaur"}, SourceLine=44)]
        public virtual void PersonalDetailsChangesUpdateClientSummary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Personal Details changes update Client Summary", null, new string[] {
                        "LoginEnableTaur"});
#line 45
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 46
 testRunner.Given("I am on Clients search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
 testRunner.And("I select the newly created client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("I click on Fact Find button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("I select the existing \"Schroders Personal Wealth Individual Fact Find\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Address1",
                        "Address2",
                        "Address3",
                        "Town",
                        "County",
                        "Postcode",
                        "Country",
                        "Telephone",
                        "Mobile",
                        "Email",
                        "Telephone Work",
                        "Fax"});
            table2.AddRow(new string[] {
                        "383 Eldon House",
                        "Wanstead",
                        "Norfolk",
                        "627814",
                        "Hampshire",
                        "8765467",
                        "United Kingdom",
                        "364654677",
                        "7880664977",
                        "a.b@creative-technologies.co.uk",
                        "6465677",
                        "65656477"});
#line 51
 testRunner.And("I edit the following client summary specific details", ((string)(null)), table2, "And ");
#line 54
 testRunner.And("I save the personal details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("I navigate to \"Clients\" via breadcrumb", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("I select the newly created client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.Then("I see that field is updated in Client Summary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Client Summary changes update Personal Details", new string[] {
                "LoginEnableTaur"}, SourceLine=59)]
        public virtual void ClientSummaryChangesUpdatePersonalDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Client Summary changes update Personal Details", null, new string[] {
                        "LoginEnableTaur"});
#line 60
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 61
 testRunner.Given("I am on Clients search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
 testRunner.And("I select the newly created client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Address1",
                        "Address2",
                        "Address3",
                        "Town",
                        "County",
                        "Postcode",
                        "Country",
                        "Telephone",
                        "Mobile",
                        "Email",
                        "Telephone Work",
                        "Fax"});
            table3.AddRow(new string[] {
                        "383 Eldon House",
                        "Wanstead",
                        "Norfolk",
                        "627814",
                        "Hampshire",
                        "8765467",
                        "United Kingdom",
                        "364654677",
                        "7880664977",
                        "a.b@creative-technologies.co.uk",
                        "6465677",
                        "65656477"});
#line 63
 testRunner.And("I edit the following client details", ((string)(null)), table3, "And ");
#line 66
 testRunner.And("I save the client details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.And("I click on Fact Find button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I select the existing \"Schroders Personal Wealth Individual Fact Find\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.When("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
    testRunner.Then("I see that field is updated in Personal Details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Personal details of a client and partner", new string[] {
                "LoginEnableTaur"}, SourceLine=72)]
        public virtual void PersonalDetailsOfAClientAndPartner()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Personal details of a client and partner", null, new string[] {
                        "LoginEnableTaur"});
#line 73
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 74
 testRunner.Given("I am on Clients search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.And("I select the newly created client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("I click on Fact Find button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I exclude the partner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I select the existing \"Schroders Personal Wealth Individual Fact Find\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I click the \"Personal Details\" from left nav", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Gender",
                        "Marital Status",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Town",
                        "County",
                        "Postcode",
                        "Country",
                        "Telephone",
                        "Date of Birth",
                        "Place of birth",
                        "UK Domiciled",
                        "UK resident for tax",
                        "State of Health",
                        "Smoker",
                        "Main occupation",
                        "Employment Status",
                        "Employer/Business name",
                        "Time in current employment"});
            table4.AddRow(new string[] {
                        "Male",
                        "Married",
                        "383 Eldon House",
                        "Wanstead",
                        "Norfolk",
                        "627814",
                        "Hampshire",
                        "8765467",
                        "United Kingdom",
                        "364654677",
                        "8-august-1993",
                        "Sussex barn",
                        "Yes",
                        "Yes",
                        "Excellent",
                        "No",
                        "refuse consultant",
                        "Employed",
                        "Best practice IFA",
                        "7 Months"});
#line 80
 testRunner.And("I enter the following personal details of client as", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Gender",
                        "Marital Status",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Town",
                        "County",
                        "Postcode",
                        "Country",
                        "Telephone",
                        "Date of Birth",
                        "Place of birth",
                        "UK Domiciled",
                        "UK resident for tax",
                        "State of Health",
                        "Smoker",
                        "Main occupation",
                        "Employment Status",
                        "Employer/Business name",
                        "Time in current employment"});
            table5.AddRow(new string[] {
                        "Male",
                        "Married",
                        "383 Eldon House",
                        "Wanstead",
                        "Norfolk",
                        "627814",
                        "Hampshire",
                        "8765467",
                        "United Kingdom",
                        "364654677",
                        "8-august-1993",
                        "Sussex barn",
                        "Yes",
                        "Yes",
                        "Excellent",
                        "No",
                        "refuse consultant",
                        "Employed",
                        "Best practice IFA",
                        "7 Months"});
#line 83
    testRunner.And("I enter the following personal details of partner as", ((string)(null)), table5, "And ");
#line 86
    testRunner.When("I save the personal details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.Then("I see the notification as \"Saved Fact Find updated successfully.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion

