var data = [
   {
      "id":"4d67e826-5c95-11e9-bd16-373537623839",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"\u05e1\u05dc\u05e7\u05d5\u05dd",
      "to":"\u05e1\u05dc\u05e7\u05d5\u05dd",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"triangle"
   },
   {
      "from":"\u05e1\u05dc\u05e7\u05d5\u05dd \u05e8\u05d0\u05e9 \u05d4\u05e2\u05d9\u05df",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"\u05e1\u05dc\u05e7\u05d5\u05dd",
      "color":"red",
      "width":"5",
      "size":"2",
      "shape":"diamond"
   },
   {
      "id":"adbc2c9c-9f9e-479e-9650-f702b8f68d5f",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"\u05e1\u05dc\u05e7\u05d5\u05dd \u05e8\u05d0\u05e9 \u05d4\u05e2\u05d9\u05df",
      "to":"\u05e1\u05dc\u05e7\u05d5\u05dd \u05e8\u05d0\u05e9 \u05d4\u05e2\u05d9\u05df",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"circle"
   },
   {
      "from":"M-02",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"\u05e1\u05dc\u05e7\u05d5\u05dd \u05e8\u05d0\u05e9 \u05d4\u05e2\u05d9\u05df",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"e0161e2e-7882-11e8-88d9-623837633865",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"M-02",
      "to":"M-02",
      "color":"green",
      "width":"2",
      "size":"3",
      "shape":"triangle"
   },
   {
      "from":"SRV20",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"3cb2400e-66ad-11e9-a85a-623335613436",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"SRV20",
      "to":"SRV20",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"MASTER-SYSLOG",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV20",
      "color":"yellow",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-5",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV20",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"rr-web3",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV20",
      "color":"grey",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"Storage-2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV20",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"GW-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"circle"
   },
   {
      "from":"SRV29",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"circle"
   },
   {
      "id":"3cb27a9c-66ad-11e9-9fa2-363033303531",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"SRV29",
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"probecules IL_D1-S1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"AllProbe - Jenkins (GIT-2)",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"IPAM",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"APR-GRID1-WEB-2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"circle"
   },
   {
      "id":"3cb285be-66ad-11e9-89b8-343632663031",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"APR-GRID1-WEB-2",
      "to":"APR-GRID1-WEB-2",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe microservice Web Cluster",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"APR-GRID1-WEB-2",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"43d0f386-7886-11e9-a4cc-373730323066",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "from":"Allprobe microservice Web Cluster",
      "to":"Allprobe microservice Web Cluster",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe microservice Daily Reports",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"Allprobe microservice Web Cluster",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"43d0ebfc-7886-11e9-baae-633962636565",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "from":"Allprobe microservice Daily Reports",
      "to":"Allprobe microservice Daily Reports",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe Overall Service",
      "status":null,
      "business_impact":null,
      "classification":null,
      "to":"Allprobe microservice Daily Reports",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"Allprobe Overall Service",
      "status":null,
      "business_impact":null,
      "classification":null,
      "to":"Allprobe microservice Web Cluster",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "from":"AllProbe Bugzila",
      "status":"offline",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"HA-PROXY2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"rr-web1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV29",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"SPARE - SWITCH",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"NFS storage",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"LAN-SWITCH-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"WAN-SWITCH-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"triangle"
   },
   {
      "from":"APR-CAS1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.SYSTEM"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"triangle"
   },
   {
      "from":"GW-2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"grey",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"HA-PROXY1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"grey",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"3cb28b7c-66ad-11e9-92b3-333662396263",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"HA-PROXY1",
      "to":"HA-PROXY1",
      "color":"grey",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe microservice Web Cluster",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"HA-PROXY1",
      "color":"grey",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"APR-CAS2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.SYSTEM"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"SRV28",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"grey",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"3cb28f0a-66ad-11e9-8c27-333261656362",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"SRV28",
      "to":"SRV28",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"diamond"
   },
   {
      "from":"APR-GRID1-WEB-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV28",
      "color":"grey",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"3cb27f6a-66ad-11e9-ad2c-613236336235",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"APR-GRID1-WEB-1",
      "to":"APR-GRID1-WEB-1",
      "color":"grey",
      "width":"2",
      "size":"3",
      "shape":"diamond"
   },
   {
      "from":"Allprobe microservice Web Cluster",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"APR-GRID1-WEB-1",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"diamond"
   },
   {
      "from":"probecules IL_D1-S3",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV28",
      "color":"lightgreen",
      "width":"2",
      "size":"2",
      "shape":"diamond"
   },
   {
      "from":"Storage-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV28",
      "color":"steelblue",
      "width":"2",
      "size":"5",
      "shape":"round"
   },
   {
      "from":"RR-SCAN-3-LEGACY",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV28",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"APR-CAS3",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.SYSTEM"
      ],
      "to":"M-02",
      "color":"lightgreen",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"SRV23",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"5",
      "size":"5",
      "shape":"round"
   },
   {
      "id":"3cb29266-66ad-11e9-ac6f-316233613337",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"SRV23",
      "to":"SRV23",
      "color":"lightgreen",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"RR-SQL-6",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV23",
      "color":"steelblue",
      "width":"2",
      "size":"5",
      "shape":"round"
   },
   {
      "from":"rr-web2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV23",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "from":"SRV27",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"lightgreen",
      "width":"5",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "id":"3cb29356-66ad-11e9-9172-353538303761",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"SRV27",
      "to":"SRV27",
      "color":"steelblue",
      "width":"2",
      "size":"5",
      "shape":"square"
   },
   {
      "from":"AllProbe-staging",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV27",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"3cb23668-66ad-11e9-be1e-383535626437",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"AllProbe-staging",
      "to":"AllProbe-staging",
      "color":"steelblue",
      "width":"2",
      "size":"4",
      "shape":"square"
   },
   {
      "from":"Allprobe microservice Daily Reports",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"AllProbe-staging",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"Allprobe microservice Cache",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"AllProbe-staging",
      "color":"steelblue",
      "width":"5",
      "size":"4",
      "shape":"round"
   },
   {
      "id":"43d0f20a-7886-11e9-a7d4-643433613932",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "from":"Allprobe microservice Cache",
      "to":"Allprobe microservice Cache",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe Overall Service",
      "status":null,
      "business_impact":null,
      "classification":null,
      "to":"Allprobe microservice Cache",
      "color":"steelblue",
      "width":"2",
      "size":"4",
      "shape":"round"
   },
   {
      "from":"probecules IL_D1-S2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV27",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"rr-web4",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"SRV27",
      "color":"steelblue",
      "width":"2",
      "size":"4",
      "shape":"round"
   },
   {
      "from":"DEBIAN-FREE-3TB",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-15",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-CAS1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"d2972738-6c4d-11e9-95dd-356131313931",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"RR-CAS1",
      "to":"RR-CAS1",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe microservice BigData",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"RR-CAS1",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"43d0f084-7886-11e9-ad89-343436386565",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "from":"Allprobe microservice BigData",
      "to":"Allprobe microservice BigData",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe Overall Service",
      "status":null,
      "business_impact":null,
      "classification":null,
      "to":"Allprobe microservice BigData",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-CAS3",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"d2972878-6c4d-11e9-b906-353863613762",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"RR-CAS3",
      "to":"RR-CAS3",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"pentagon"
   },
   {
      "from":"Allprobe microservice BigData",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"RR-CAS3",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "from":"RR-ELS-8",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "from":"RR-ELS-9",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-9",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"lightgreen",
      "width":"2",
      "size":"2",
      "shape":"square"
   },
   {
      "from":"RR-ELS-2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"lightgreen",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-ELS-3",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"square"
   },
   {
      "from":"RR-CAS2",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"pink",
      "width":"5",
      "size":"2",
      "shape":"round"
   },
   {
      "id":"d297312e-6c4d-11e9-9391-663630393536",
      "status":"online",
      "business_impact":"1",
      "classification":[
         "CI.NONE"
      ],
      "from":"RR-CAS2",
      "to":"RR-CAS2",
      "color":"steelblue",
      "width":"2",
      "size":"3",
      "shape":"square"
   },
   {
      "from":"Allprobe microservice BigData",
      "status":"online",
      "business_impact":[
         "medium"
      ],
      "classification":[
         "CI.BUSINESSPROCESS"
      ],
      "to":"RR-CAS2",
      "color":"pink",
      "width":"5",
      "size":"4",
      "shape":"round"
   },
   {
      "from":"RR-CAS5 - seed",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"diamond"
   },
   {
      "from":"RR-ELS-1",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"pink",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-CAS4 - seed",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-11",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"pink",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-12",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-ELS-5 + Kibana",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"pink",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-ELS-4",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-8",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"triangle"
   },
   {
      "from":"RR-SQL-3",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"triangle"
   },
   {
      "from":"RR-SQL-10",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "from":"RR-ELS-6",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"pentagon"
   },
   {
      "from":"RR-ELS-7",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"round"
   },
   {
      "from":"RR-SQL-4",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"steelblue",
      "width":"2",
      "size":"2",
      "shape":"square"
   },
   {
      "from":"RR-SQL-7",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"M-02",
      "color":"pink",
      "width":"2",
      "size":"2",
      "shape":"circle"
   },
   {
      "from":"M-02",
      "status":"online",
      "business_impact":null,
      "classification":[
         "CI.NONE"
      ],
      "to":"\u05e1\u05dc\u05e7\u05d5\u05dd",
      "color":"steelblue",
      "width":"5",
      "size":"2",
      "shape":"pentagon"
   }
];